<html>
<head>
	<title>Video-on-Demand Host</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" 
		integrity="sha384-nn4HPE8lTHyVtfCBi5yW9d20FjT8BJwUXyWZT9InLYax14RDjBj46LmSztkmNP9w" crossorigin="anonymous">

	<link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
	<link rel="stylesheet" href="/static/css/main.css">
</head>

<body>

<?php include 'src/templates/topnav.phtml' ?>

<div><h1>g</h1></div>

<div class="pure-g">
	<div class="pure-u-1-3"><h3></h3></div>

	<div class="pure-u-1-3">
		<div class="centerdiv">
			<h3>Login</h3>
			<form class="pure-form pure-form-stacked" method="post" action="/attempt_login">
			    <fieldset>
			        <legend>Login to your VodHost account</legend>

			        <label for="email">Email</label>
			        <input id="email" name="email" type="email" placeholder="Email" required>

			        <label for="password">Password</label>
			        <input id="password" name="password" type="password" placeholder="Password" required>

			        <label for="remember" class="pure-checkbox">
			            <input id="remember" name="remember" type="checkbox"> Remember me
			        </label>

			        <button type="submit" class="pure-button pure-button-primary">Sign in</button>
			    </fieldset>
			</form>
		</div>
	</div>
</div>

</body>
</html>