<!DOCTYPE html>
<html>
<head>
	<title>Video-on-Demand Host</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" 
		integrity="sha384-nn4HPE8lTHyVtfCBi5yW9d20FjT8BJwUXyWZT9InLYax14RDjBj46LmSztkmNP9w" crossorigin="anonymous">

	<link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
	<link rel="stylesheet" href="/static/css/main.css">
	<link rel="stylesheet" href="/static/css/side-menu.css">

	<script src="/static/jsvendor/angular.min.js"></script>
</head>

<body ng-app="account" ng-controller="accountCtrl">

<script>
var app = angular.module('account', []);
app.controller('accountCtrl', function($scope, $http, $window, $parse) {

	$scope.contenturl = "<?php echo $content_url; ?>";

	var panes = [
		"showUserInfo",
		"showNotifications",
		"showSubscriptions",
		"showVideos",
		"showClips"
	];

	fetchAllInfo();

	// Show the first pane by default (user info)
	$parse(panes[0]).assign($scope, true);

	function fetchAllInfo() {
		$http.get("api/account/getinfo").then(function(response) {
			var data = $scope.$eval(response.data);

			/* Correctly format the broadcast upload dates */
			data.broadcasts.forEach(function(b) {
				var dateObj = new Date(b.upload_date.date);

				// hack: this will break after the year 10,000
				b.upload_date = dateObj.toISOString().substring(0,10);
			});

			$scope.user = data.user;
			$scope.broadcasts = data.broadcasts;
		});
	}

	$scope.showPane = function(id) {
		panes.forEach(function(element) {
			var ng_exp = $parse(element);

			if(id == panes.indexOf(element)) {
				ng_exp.assign($scope, true);
			} else {
				ng_exp.assign($scope, false);
			}
		});
	}

	$scope.removeVideo = function(videoid) {
		if(confirm("Are you sure you want to delete this video?")) {
			var endpoint = 'api/broadcast/remove';

			var postdata = {
	        	"videoid": videoid
        	};

			$http.post(endpoint, postdata).then(function(response) {
				if(response.status == 200) {
					fetchAllInfo();
				}
			}).catch(function(error, status) {
				alert("Unfortunately, an error occurred. Please try again later");
			});
		}
	};

	$scope.editVideo = function(video) {
		$scope.editvideo = video;
		$scope.editDarkOverlay = true;

		$scope.editingtitle = video.title;
		$scope.editingdesc = video.description;
		$scope.editingvis = "Private";
		if(video.visibility) {
			$scope.editingvis = "Public";
		}
	};

	// make this an array moron
	$scope.cancelEdit = function() {
		$scope.editDarkOverlay = false;

		$scope.editvideo = null;
		$scope.editingtitle = null;
		$scope.editingdesc = null;
		$scope.editingvis = null;
	};

	$scope.saveVideoChanges = function() {
		var endpoint = 'api/broadcast/editdetails';
		var postdata = {
        	"videoid": $scope.editvideo.id,
        	"title": $scope.editingtitle,
        	"description": $scope.editingdesc,
        	"visibility": $scope.editingvis
    	};

    	$http.post(endpoint, postdata).then(function(response) {
			if(response.status == 200) {
				fetchAllInfo();
			}
			$scope.cancelEdit(); // Close the pane
		}).catch(function(error, status) {
			alert("Unfortunately, an error occurred. Please try again later");
			$scope.cancelEdit(); // Close the pane
		});
	}
});
</script>

<div class="editoverlay" ng-show="editDarkOverlay"></div>
<div class="editpanel" ng-show="editDarkOverlay">

	<div class="editpanel-left">
		<img height="115px" ng-src="{{contenturl + '/thumb/' + editvideo.id + '/thumb_2.jpg'}}"></img>
		<p>{{editvideo.upload_date}}</p>
		<p>Length: {{editvideo.length}}</p>
		<p>{{editvideo.filesize}}MB</p>
	</div>

	<div class="editpanel-right">
		<form class="pure-form pure-form-stacked">
			<fieldset class="pure-group">
				<input class="pure-input-2-3" ng-model="editingtitle" id="title" name="title" type="text" placeholder="My Video" required><br />
				<textarea class="pure-input-1" ng-model="editingdesc" id="desc" name="desc" placeholder="Description" rows="10"></textarea><br />
				<select id="visibility" ng-model="editingvis">
		            <option>Public</option>
		            <option>Private</option>
		        </select>
			</fieldset>
		</form>

		<button ng-click="saveVideoChanges()" class="pure-button pure-button-primary">Save</button>
		<button ng-click="cancelEdit()" class="pure-button pure-button-primary">Cancel</button>
	</div>
</div>

<?php include __DIR__ . '/topnav.phtml' ?>

<br />

<div id="layout">

    <div id="menu">
	    <div class="pure-menu">
	    <span class="pure-menu-heading">Settings</span>
	        <ul class="pure-menu-list">
	            <li class="pure-menu-item"><a href="#" ng-click="showPane(0)" class="pure-menu-link">User Details</a></li>
	            <li class="pure-menu-item"><a href="#" ng-click="showPane(1)" class="pure-menu-link">Notifications</a></li>
	            <li class="pure-menu-item"><a href="#" ng-click="showPane(2)" class="pure-menu-link">Subscriptions</a></li>
	            <li class="pure-menu-item"><a href="#" ng-click="showPane(3)" class="pure-menu-link">My Videos</a></li>
	            <li class="pure-menu-item"><a href="#" ng-click="showPane(4)" class="pure-menu-link">Clips</a></li>
	        </ul>
	    </div>
	</div>

	<div id="main">
        <div class="content" ng-show="showUserInfo">
            <h2 class="content-subhead">Account Overview - {{user.username}}</h2>
            <p><strong>Username:</strong> {{user.username}}</p>
            <p><strong>Email:</strong> {{user.email}}</p>
            <p><strong>Account verified:</strong> {{user.activated}}</p>
            <p><strong>Date Registered:</strong> (stub)</p>
            <p><strong>Videos Uploaded:</strong> (stub)</p>
            <p><strong>Subscribers:</strong> (stub)</p>
        </div>

        <div class="content" ng-show="showNotifications">
            <h2 class="content-subhead">Notification Settings</h2>
            <p><strong>Get notifications on:<strong></p>
            <label for="sub" class="pure-checkbox">
	            <input id="sub" name="remember" type="checkbox"> New subscription content
	        </label>
	        <br />
	        <label for="newsub" class="pure-checkbox">
	            <input id="newsub" name="remember" type="checkbox"> New subscribers
	        </label>

	        <p><strong>Send notifications by:<strong></p>
	        <label for="email" class="pure-checkbox">
	            <input id="email" name="remember" type="checkbox"> Email
	        </label>
	        <br />
	        <label for="push" class="pure-checkbox">
	            <input id="push" name="remember" type="checkbox"> Push Notifications
	        </label>
	        <br /><br />
	        <button ng-click="saveNotifications()" class="pure-button pure-button-primary">Apply</button>
        </div>

        <div class="content" ng-show="showSubscriptions">
            <h2 class="content-subhead">Feature not yet implemented</h2>
        </div>

        <div class="content" ng-show="showVideos">
            <h2 class="content-subhead">Broadcasts</h2>

            	<div class="videogrid" ng-repeat="video in broadcasts">
            		<img height="90px" class="videothumb" ng-src="{{contenturl + '/thumb/' + video.id + '/thumb_2.jpg'}}"></img>
            		<div class="videostats">
            			<p>Views: {{video.views}}</p>
            			<p>Uploaded: {{video.upload_date}}</p>
            			<p>Public: {{video.visibility}}</p>
            		</div>
            		<div class="videoinfo">
            			<p><strong>{{video.title}}</strong></p>
            			<p>{{video.description}}</p>
            		</div>
            		<div class="videoactions">
            			<button ng-click="editVideo(video)" class="pure-button pure-button-primary">Edit</button>
            			<br />
            			<button ng-click="removeVideo(video.id)" class="pure-button pure-button-primary">Remove</button>
            		</div>
            	</div>
        </div>

        <div class="content" ng-show="showClips">
            <h2 class="content-subhead">Feature not yet implemented</h2>
        </div>
	</div>

</div>


</body>
</html>