<!DOCTYPE html>
<html>
<head>
	<title>Video-on-Demand Host</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" 
		integrity="sha384-nn4HPE8lTHyVtfCBi5yW9d20FjT8BJwUXyWZT9InLYax14RDjBj46LmSztkmNP9w" crossorigin="anonymous">

	<link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
	<link rel="stylesheet" href="/static/css/main.css">

	<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular.js"></script>
</head>

<script>
	var app = angular.module("ng-frontPage", []);

	app.controller("frontPageCtrl", function($scope, $http) {
		$http.get("api/fetch/recentvideos")
	    .then(function(response) {
	    	$scope.broadcasts = $scope.$eval(response.data);
	    	$scope.contenturl = "<?php echo $content_url; ?>";
	    });
});
</script>

<body>

<?php include 'src/templates/topnav.phtml' ?>

<div class="headershim"><h2>Recent Uploads</h2></div>

<div ng-app="ng-frontPage" ng-controller="frontPageCtrl">

	<div class="videolist">
		<ul>
			<li ng-repeat="video in broadcasts">
				<div class="videocard">
						<a href="/view/{{video.id}}"><img src="{{contenturl}}/thumb/{{video.id}}/thumb_0.jpg"></img>
						<h4>{{video.title}}</h4></a>
				</div>
			</li>
		</ul>
	</div>
</div>

</body>
</html>