<html>
<head>
	<title>Video-on-Demand Host</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" 
		integrity="sha384-nn4HPE8lTHyVtfCBi5yW9d20FjT8BJwUXyWZT9InLYax14RDjBj46LmSztkmNP9w" crossorigin="anonymous">

	<link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
	<link rel="stylesheet" href="/static/css/main.css">

	<script src="/static/jsvendor/angular.min.js"></script>
</head>

<body>

<script>
var app = angular.module('login', []);
app.controller('loginCtrl', function($scope, $http, $window) {
	$scope.error_text = "";

    $scope.login = function() {
        var data = {
        	"email":$scope.email,
        	"password":$scope.password
        };

        var url = '/api/signin';

        $http.post(url, data, { withCredentials: true }).then(function(msg) {
        	if(msg.data['state'] == 'error')
        		$scope.error_text = msg.data['message'];
        	else if(msg.data['state'] == 'success')
        		$window.location.href = '/';
        });
    }
});
</script>

<?php include 'src/templates/topnav.phtml' ?>

<br /><br />

<div class="pure-g">
	<div class="pure-u-1-3"><h3></h3></div>

	<div ng-app="login" ng-controller="loginCtrl" class="pure-u-1-3">
		<div class="centerdiv">
			<h3>Login</h3>
			<form class="pure-form pure-form-stacked">
			    <fieldset>
			        <legend>Login to your VodHost account</legend>

			        <p class="rederror">{{error_text}}</p>

			        <label for="email">Email</label>
			        <input ng-model="email" id="email" name="email" type="email" placeholder="Email" required>

			        <label for="password">Password</label>
			        <input ng-model="password" id="password" name="password" type="password" placeholder="Password" required>

			        <label for="remember" class="pure-checkbox">
			            <input id="remember" name="remember" type="checkbox"> Remember me
			        </label>

			        <button ng-click="login()" class="pure-button pure-button-primary">Sign in</button>
			    </fieldset>
			</form>
		</div>
	</div>
</div>

</body>
</html>