<!DOCTYPE html>
<html id="ng-app" ng-app="app" ng-controller="uploadCtrl" flow-init>
<head>
	<title>Video-on-Demand Host</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" 
		integrity="sha384-nn4HPE8lTHyVtfCBi5yW9d20FjT8BJwUXyWZT9InLYax14RDjBj46LmSztkmNP9w" crossorigin="anonymous">

	<link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
	<link rel="stylesheet" href="/static/css/main.css">

	<script src="/static/jsvendor/angular.min.js"></script>
    <script src="/static/jsvendor/ng-flow-standalone.js"></script>
    <script src="/static/js/uploader.js"></script>
</head>

<body flow-prevent-drop ng-style="style">

<?php include __DIR__ . '/topnav.phtml' ?>

<br /><br />

<div class="pure-g">
	<div class="pure-u-1-3">
		<table class="table table-hover table-bordered table-striped" flow-transfers>
			<thead>
				<tr>
					<th>Name</th>
					<th>Size</th>
					<th>Progress</th>
				</tr>
			</thead>
			<tbody>
				<tr ng-repeat="file in transfers">
					<td>{{file.name}}</td>
					<td>{{(file.size / 1024 / 1024) | number:1}} MB</td>
					<td>{{file.progress()}}</td>
				</tr>
			</tbody>
		</table>

	</div>

	<div class="pure-u-1-3">
		<div class="centerdiv">
			<h3>Upload</h3>

			<div class="row">
				<div class="span6">

					<span class="btn" flow-btn><i class="icon icon-file"></i>Upload File</span>
				</div>
			</div>

			<hr class="soften">

			<h2>Transfer:</h2>

			<p>
				<a class="btn btn-small btn-success" ng-click="$flow.resume()">Upload</a>
				<a class="btn btn-small btn-danger" ng-click="$flow.pause()">Pause</a>
			</p>
			
		</div>
	</div>

	<div class="pure-u-1-3"><h3>Video Information</h3>
		<form class="pure-form pure-form-stacked">
			<fieldset class="pure-group">
				<label for="title">Video Title</label>
				<input ng-model="title" id="title" name="title" type="text" placeholder="My Video" required><br />
				<textarea class="pure-input-1-2" ng-model="desc" id="desc" name="desc" placeholder="Description"></textarea>
			</fieldset>

			<a class="btn" ng-click="saveInfo()">Save</a>
		</form>
	</div>
</div>

	<hr class="soften"/>

</body>
</html>