<html>
<head>
	<title>Video-on-Demand Host</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" 
		integrity="sha384-nn4HPE8lTHyVtfCBi5yW9d20FjT8BJwUXyWZT9InLYax14RDjBj46LmSztkmNP9w" crossorigin="anonymous">
   
    <link href="http://vjs.zencdn.net/6.4.0/video-js.css" rel="stylesheet">
    <script src="http://vjs.zencdn.net/6.4.0/video.min.js"></script>
	<!-- IE8 support -->
	<script src="http://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>


	<link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
	<link rel="stylesheet" href="/static/css/main.css">
	<link rel="stylesheet" href="/static/css/video.css">
</head>


<body>

	<?php include 'src/templates/topnav.phtml' ?>

	<div class="headershim"></div>

	<div class="videoholder">
		<video id="video" class="video-js vjs-default-skin vjs-fluid" controls preload="auto" width="1024px" height="576px" data-setup='{"fluid": true, "playbackRates": [1, 1.5, 2]}'>
			<source src=<?php echo "$media_path" ?> type='video/mp4'>

			<p class="vjs-no-js">
				To view this video please enable JavaScript, and consider upgrading to a web browser that
				<a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
			</p>
		</video>

		<br /><hr />

		<h4><?php echo "$media_title" ?></h4>
		<h7>Uploaded by <strong><?php echo "$media_uploader" ?></strong></h4>
		<p><?php echo "$media_desc" ?></p>
		<h7><?php echo "$media_views" ?> views</h7>
		<br /><hr />
	</div>


</body>
</html>