<!DOCTYPE html>
<html>
<head>
	<title>Video-on-Demand Host</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" 
		integrity="sha384-nn4HPE8lTHyVtfCBi5yW9d20FjT8BJwUXyWZT9InLYax14RDjBj46LmSztkmNP9w" crossorigin="anonymous">

	<link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
	<link rel="stylesheet" href="/static/css/main.css">
</head>

<body>

<?php include __DIR__ . '/topnav.phtml' ?>

<br />

<?php

if($validCode) {
	echo '
	<div class="centerdivtext">
		<h3>Account Verification</h3>
		<p>Your account has been verified</p>
		<p>Click <a href="/login">Here</a> to Sign in</p>
	</div>
	';
} else {
	echo '
	<div class="centerdivtext">
		<h3>Account Verification</h3>
		<p>Sorry, this verification code appears to have expired</p>
	</div>
	';
}
?>

</body>
</html>