<!DOCTYPE html>
<html id="ng-app" ng-app="app" ng-controller="uploadCtrl" flow-init>
<head>
	<title>Video-on-Demand Host</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" 
		integrity="sha384-nn4HPE8lTHyVtfCBi5yW9d20FjT8BJwUXyWZT9InLYax14RDjBj46LmSztkmNP9w" crossorigin="anonymous">

	<link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
	<link rel="stylesheet" href="/static/css/main.css">
	<link rel="stylesheet" href="/static/css/upload.css">
	<link rel="stylesheet" href="/static/css/progress-bar.css">

	<script src="/static/jsvendor/angular.min.js"></script>
    <script src="/static/jsvendor/ng-flow-standalone.js"></script>
    <script src="/static/js/uploader.js"></script>

     <style>
            .my-drop-zone { border: dotted 3px lightgray; padding: 19px; background-color: #eeeeee; text-align: center; height: 400px; border-radius: 12px; margin-left: 2em; margin-right: 2em;}
            .nv-file-over { border: dotted 3px red; } /* Default class applied to drop zones on over */
            .another-file-over-class { border: dotted 3px green; }
    </style>
</head>

<body flow-prevent-drop ng-style="style">

<?php include __DIR__ . '/topnav.phtml' ?>

<br /><br />

<div id="layout" ng-show="selectFile">
	<div class="my-drop-zone" flow-drop>
    	<h3>Drag And Drop your file here</h3>
	</div>
	<h4> Alternatively </h4>
	<button flow-btn class="pure-button pure-button-primary">Select File</button>
</div>

<div id="layout" ng-show="setProperties">
	<div id="content-left" flow-transfers>
		<h3>{{transfers[0].name}}</h3>

		<p>Size: {{(transfers[0].size / 1024 / 1024) | number:1}} MB</p>

		<!-- deal with it -->
		<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />

		<h3>Progress</h3>
		<div class="progress-bar">
			<span ng-style="{width: (transfers[0].progress() * 100) + '%'}"></span>
		</div>
	</div>

	<div id="content-right">
		<form class="pure-form pure-form-stacked">
			<input ng-disabled="inputDisabled" ng-model="title" id="title" name="title" type="text" placeholder="My Video Title" required><br />
			<br />
			<textarea ng-disabled="inputDisabled" class="pure-input-2-3" rows="11" ng-model="desc" id="desc" name="desc" placeholder="Video Description goes here."></textarea>
			<select ng-disabled="inputDisabled" ng-model="vis" required ng-options='option.value as option.name for option in visOptions'>
	        </select>

		</form>
		<button ng-disabled="inputDisabled" ng-click="onUploadClicked($flow)" class="pure-button pure-button-primary">Upload</button>
	</div>
</div>

</body>
</html>