<!DOCTYPE html>
<html>
<head>
	<title>Video-on-Demand Host</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css"
		integrity="sha384-nn4HPE8lTHyVtfCBi5yW9d20FjT8BJwUXyWZT9InLYax14RDjBj46LmSztkmNP9w" crossorigin="anonymous">

	<link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
	<link rel="stylesheet" href="/static/css/main.css">

	<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular.js"></script>
</head>

<script>
	var app = angular.module("ng-frontPage", []);

	app.controller("frontPageCtrl", function($scope, $http, $interval) {
		$http.get("api/broadcast/fetchrecent")
	    .then(function(response) {
	    	$scope.broadcasts = $scope.$eval(response.data);
	    	$scope.broadcasts.forEach(function(video) {
	    		var videoDate = new Date(video.upload_date.date);
	    		var curDate = new Date();
	    		var dif = Math.floor((curDate.getTime() - videoDate.getTime()) / 1000);

	    		video.upload_date = 'date unparsed';

	    		if(dif < 60) {
	    			video.upload_date = dif + ' seconds ago';
	    		} else if (dif < 60*60) {
	    			video.upload_date = Math.floor(dif/60) + ' minutes ago';
	    		} else if (dif < 60*60*24) {
	    			video.upload_date = Math.floor(dif/60/60) + ' hours ago';
	    		} else if (dif < 60*60*24*30) {
	    			video.upload_date = Math.floor(dif/60/60/24) + ' days ago';
	    		} else if (dif < 60*60*24*30*12) {
	    			video.upload_date = Math.floor(dif/60/60/24/30) + ' months ago';
	    		} else {
	    			video.upload_date = Math.floor(dif/60/60/24/30/12) + ' years ago';
	    		}

	    	});

	    	$scope.contenturl = "<?php echo $content_url; ?>";
	    });


	    var anim_video;
	    var anim_i;

	    var animateThumbFunc;

	    $scope.startAnimateThumb = function(video) {
        	anim_video = video;
        	anim_i=1;

        	animateThumbFunc = $interval(function () {
		        anim_video.thumb = ($scope.contenturl + '/thumb/' + video.id + '/thumb_' + anim_i + '.jpg')
		        anim_i += 1;
		        if(anim_i >= 5)
		        	anim_i = 0;
		    }, 500);
        }

        $scope.stopAnimateThumb = function(video) {
        	video.thumb = ($scope.contenturl + '/thumb/' + video.id + '/thumb_0.jpg')
        	$interval.cancel(animateThumbFunc);
        }

		$scope.getThumbSrc = function(video) {
			if(!video) {
				return;
			}

			if(video.state == 'processing') {
				return '/static/img/processing_thumb.png';
			} else {
				if(video.thumb) {
					return video.thumb;
				} else {
					return $scope.contenturl + '/thumb/' + video.id + '/thumb_0.jpg';
				}
			}
		}
	});
</script>

<body>

<?php include __DIR__ . '/topnav.phtml' ?>

<div class="headershim"><h2>Recent Uploads</h2></div>

<div ng-app="ng-frontPage" ng-controller="frontPageCtrl">

	<div class="videolist">
		<ul>
			<li ng-repeat="video in broadcasts">
				<div class="videocard" ng-mouseenter="startAnimateThumb(video)" ng-mouseleave="stopAnimateThumb(video)">
						<a href="/view/{{video.id}}"><img ng-src="{{getThumbSrc(video)}}"></img>
						<h4>{{video.title}}</h4></a>
						<h7>Uploaded by: <strong>{{video.uploader}}</strong></h7><br />
						<h7>{{video.views}} views &#8226; {{video.upload_date}}</h7>
				</div>
			</li>
		</ul>
	</div>
</div>

</body>
</html>
