<html>
<head>
	<title>Video-on-Demand Host</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" 
		integrity="sha384-nn4HPE8lTHyVtfCBi5yW9d20FjT8BJwUXyWZT9InLYax14RDjBj46LmSztkmNP9w" crossorigin="anonymous">

	<link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
	<link rel="stylesheet" href="/static/css/main.css">

	<script src="/static/jsvendor/angular.min.js"></script>
</head>

<body>

<script>
var app = angular.module('registrar', []);
app.controller('regCtrl', function($scope, $http, $window) {
	$scope.error_text = "";

    $scope.register = function() {
        var data = {
        	"username":$scope.username,
        	"email":$scope.email,
        	"password":$scope.password
        };

        var url = '/api/signup'

        $http.post(url, data).then(function(msg) {
        	if(msg.data['state'] == 'error')
        		$scope.error_text = msg.data['message'];
        	else if(msg.data['state'] == 'success')
        		$window.location.href = '/';
        });
    }
});
</script>

<?php include __DIR__ . '/topnav.phtml' ?>

<br /><br />

<div class="pure-g">
	<div class="pure-u-1-3"><h3></h3></div>

	<div ng-app="registrar" ng-controller="regCtrl" class="pure-u-1-3">
		<div class="centerdiv">
			<h3>Register</h3>
			<form class="pure-form pure-form-stacked">
			    <fieldset>
			        <legend>Register a VodHost account</legend>

			        <p class="rederror">{{error_text}}</p>

			        <label for="email">Email</label>
			        <input ng-model="email" id="email" name="email" type="email" placeholder="Email" required>

			        <br />

			        <label for="username">Username</label>
			        <span class="pure-form-message">This is a required field.</span>
			        <input ng-model="username" id="username" name="username" type="text" placeholder="Username" required>

			        <label for="password">Password</label>
			        <input ng-model="password" id="password" name="password" type="password" placeholder="Password" required>

			        <br />
			        <button ng-click="register()" class="pure-button pure-button-primary">Create Account</button>
			    </fieldset>
			</form>
		</div>
	</div>
	<div class="pure-u-1-3"><h3></h3></div>
</div>

</body>
</html>